server:
  port: 8086

spring:
  application:
    name: hystrix-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8050/eureka/

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000

#监控
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'